/*  -------------------------------------------------- */
/*  Generated by Enterprise Architect Version 7.1.829*/
/*  Created On : Tuesday, 27 August, 2013 */
/*  DBMS       : MySql */
/*  -------------------------------------------------- */

DROP TABLE IF EXISTS clerk
;
CREATE TABLE clerk
(
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(24),
	password VARCHAR(12),
	role VARCHAR(3),
	phone VARCHAR(14),
	PRIMARY KEY (id)
) 
;


