<?php
$ORGNAME = "Royal Oak Manor Showcase Boutique";
$ORGADDRESS = "606 Williams";
$ORGCITY = "Royal Oak";
$ORGSTATE = "Michigan";
$ORGZIP = "48067";
$ORGTOPPHRASE = "Thank You for shopping with us";
$ORGBOTOMPHRASE = "Come back soon";
define('ORGNAME_DEF','Royal Oak Manor Showcase Boutique);
define('ORGADDRESS_DEF', '606 Williams');
define('ORGCITY_DEF', 'Royal Oak');
define('ORGSTATE_DEF' , 'Michigan');
define('ORGZIP_DEF' , '48067');
define('ORG_TOP_PHRASE' , 'Thanks for shopping with us');
define('ORG_BOTTOM_PHRASE' , 'Come back soon');

?>
