/*  -------------------------------------------------- */
/*  Generated by Enterprise Architect Version 7.1.829*/
/*  Created On : Tuesday, 27 August, 2013 */
/*  DBMS       : MySql */
/*  -------------------------------------------------- */

DROP TABLE IF EXISTS department
;
CREATE TABLE department
(
	id INTEGER NOT NULL AUTO_INCREMENT,
	name CHAR(24),
	taxid1 INTEGER,
	taxid2 INTEGER,
	PRIMARY KEY (id)
) 
;


