	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv='Content-Type' content='text/html; charset=utf-8'>
	<!--<META HTTP-EQUIV="Pragma" CONTENT="no-cache">
	<META HTTP-EQUIV="Expires" CONTENT="-1">-->
	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
	<link rel="stylesheet" href="../datepicker/jquery.ui.datepicker.mobile.css" /> 
	<link rel="stylesheet" href="register.css">
	<!--<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">-->
	
	<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.js"></script>
	<script src-"http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>	
	<!--<script language="javascript" src="../jsound/jsound/jquery18.js"></script>
	<script language="javascript" src="../jsound/jsound/jsound.js"></script>-->
	<!--<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>-->
	<script src="../datepicker/jQuery.ui.datepicker.js"></script>
  	<script src="../datepicker/jquery.ui.datepicker.mobile.js"></script>
	<script src="../dough/Dough/dough.js"></script>
	
	
  
	