/*  -------------------------------------------------- */
/*  Generated by Enterprise Architect Version 7.1.829*/
/*  Created On : Sunday, 01 September, 2013 */
/*  DBMS       : MySql */
/*  -------------------------------------------------- */

DROP TABLE IF EXISTS sales
;
CREATE TABLE sales
(
	id INTEGER NOT NULL AUTO_INCREMENT,
	recieved DECIMAL(7,2) NOT NULL DEFAULT 0.00,
	tax DECIMAL(7,2) NOT NULL DEFAULT 0.00,
	amount DECIMAL(10,2),
	change_remitted DECIMAL(10,2),
	transactions VARCHAR(50),
	PRIMARY KEY (id)